#!/bin/bash

# Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain

set +e

boot_anim=""
fail_counter=0
timeout_in_sec=60

until [[ "$boot_anim" =~ "stopped" ]]; do
  boot_anim=$(adb -e shell getprop init.svc.bootanim 2>&1 &)
  ((fail_counter += 1))
  echo "Waiting for emulator to start ($boot_anim)"
  if [[ $fail_counter -gt timeout_in_sec ]]; then
    echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
    exit 1
  fi
  sleep 1
done

echo "Emulator is ready"
