#!/bin/bash
# Script adb-all
# Taken from https://stackoverflow.com/a/8672540/859027
# Usage
# You can run any command adb provide on all your current devices
# ./adb-all <command> is the equivalent of ./adb -s <serial number> <command>
#
# Examples
# ./adb-all version
# ./adb-all install apidemo.apk
# ./adb-all uninstall com.example.android.apis

adb devices | while read -r line; do
  if [ ! "$line" = "" ] && [ "$(echo "$line" | awk '{print $2}')" = "device" ]; then
    device=$(echo "$line" | awk '{print $1}')
    echo "$device $* ..."
    adb -s "$device" "$@"
  fi
done
