#!/bin/bash
android-avdmanager-create "avdmanager create avd --package \"$ANDROID_EMULATOR_PACKAGE\" --name test --abi \"google_apis_playstore/x86_64\""
emulator -avd test -no-audio -no-boot-anim -no-window -accel on -gpu off &
android-wait-for-emulator
adb shell input keyevent 82
